/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class comunicacionlan_ComunicacionLAN */

#ifndef _Included_comunicacionlan_ComunicacionLAN
#define _Included_comunicacionlan_ComunicacionLAN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comunicacionlan_ComunicacionLAN
 * Method:    OpenPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_comunicacionlan_ComunicacionLAN_OpenPort
  (JNIEnv *, jclass);

/*
 * Class:     comunicacionlan_ComunicacionLAN
 * Method:    ClosePort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_comunicacionlan_ComunicacionLAN_ClosePort
  (JNIEnv *, jclass);

/*
 * Class:     comunicacionlan_ComunicacionLAN
 * Method:    SetPosition
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_comunicacionlan_ComunicacionLAN_SetPosition
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     comunicacionlan_ComunicacionLAN
 * Method:    ExecuteJob
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_comunicacionlan_ComunicacionLAN_ExecuteJob
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
